// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: config.proto

#ifndef PROTOBUF_config_2eproto__INCLUDED
#define PROTOBUF_config_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace Pmd {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_config_2eproto();
void protobuf_AssignDesc_config_2eproto();
void protobuf_ShutdownFile_config_2eproto();

class Config;

enum Config_Version {
  Config_Version_Version_Login = 20150912,
  Config_Version_Version_Game = 20150912,
  Config_Version_Version_Gm = 20150912,
  Config_Version_Version_Gateway = 20150912,
  Config_Version_Version_NameS = 20150912,
  Config_Version_Version_Monitor = 20150912,
  Config_Version_Version_Sdk = 20150912,
  Config_Version_Version_Build = 20150912,
  Config_Version_Version_Logger = 20160626
};
bool Config_Version_IsValid(int value);
const Config_Version Config_Version_Version_MIN = Config_Version_Version_Login;
const Config_Version Config_Version_Version_MAX = Config_Version_Version_Logger;
const int Config_Version_Version_ARRAYSIZE = Config_Version_Version_MAX + 1;

const ::google::protobuf::EnumDescriptor* Config_Version_descriptor();
inline const ::std::string& Config_Version_Name(Config_Version value) {
  return ::google::protobuf::internal::NameOfEnum(
    Config_Version_descriptor(), value);
}
inline bool Config_Version_Parse(
    const ::std::string& name, Config_Version* value) {
  return ::google::protobuf::internal::ParseNamedEnum<Config_Version>(
    Config_Version_descriptor(), name, value);
}
enum Config_Debug {
  Config_Debug_Debug_All = 1,
  Config_Debug_Debug_Whj = 1
};
bool Config_Debug_IsValid(int value);
const Config_Debug Config_Debug_Debug_MIN = Config_Debug_Debug_All;
const Config_Debug Config_Debug_Debug_MAX = Config_Debug_Debug_All;
const int Config_Debug_Debug_ARRAYSIZE = Config_Debug_Debug_MAX + 1;

const ::google::protobuf::EnumDescriptor* Config_Debug_descriptor();
inline const ::std::string& Config_Debug_Name(Config_Debug value) {
  return ::google::protobuf::internal::NameOfEnum(
    Config_Debug_descriptor(), value);
}
inline bool Config_Debug_Parse(
    const ::std::string& name, Config_Debug* value) {
  return ::google::protobuf::internal::ParseNamedEnum<Config_Debug>(
    Config_Debug_descriptor(), name, value);
}
// ===================================================================

class Config : public ::google::protobuf::Message {
 public:
  Config();
  virtual ~Config();

  Config(const Config& from);

  inline Config& operator=(const Config& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Config& default_instance();

  void Swap(Config* other);

  // implements Message ----------------------------------------------

  Config* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Config& from);
  void MergeFrom(const Config& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef Config_Version Version;
  static const Version Version_Login = Config_Version_Version_Login;
  static const Version Version_Game = Config_Version_Version_Game;
  static const Version Version_Gm = Config_Version_Version_Gm;
  static const Version Version_Gateway = Config_Version_Version_Gateway;
  static const Version Version_NameS = Config_Version_Version_NameS;
  static const Version Version_Monitor = Config_Version_Version_Monitor;
  static const Version Version_Sdk = Config_Version_Version_Sdk;
  static const Version Version_Build = Config_Version_Version_Build;
  static const Version Version_Logger = Config_Version_Version_Logger;
  static inline bool Version_IsValid(int value) {
    return Config_Version_IsValid(value);
  }
  static const Version Version_MIN =
    Config_Version_Version_MIN;
  static const Version Version_MAX =
    Config_Version_Version_MAX;
  static const int Version_ARRAYSIZE =
    Config_Version_Version_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  Version_descriptor() {
    return Config_Version_descriptor();
  }
  static inline const ::std::string& Version_Name(Version value) {
    return Config_Version_Name(value);
  }
  static inline bool Version_Parse(const ::std::string& name,
      Version* value) {
    return Config_Version_Parse(name, value);
  }

  typedef Config_Debug Debug;
  static const Debug Debug_All = Config_Debug_Debug_All;
  static const Debug Debug_Whj = Config_Debug_Debug_Whj;
  static inline bool Debug_IsValid(int value) {
    return Config_Debug_IsValid(value);
  }
  static const Debug Debug_MIN =
    Config_Debug_Debug_MIN;
  static const Debug Debug_MAX =
    Config_Debug_Debug_MAX;
  static const int Debug_ARRAYSIZE =
    Config_Debug_Debug_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  Debug_descriptor() {
    return Config_Debug_descriptor();
  }
  static inline const ::std::string& Debug_Name(Debug value) {
    return Config_Debug_Name(value);
  }
  static inline bool Debug_Parse(const ::std::string& name,
      Debug* value) {
    return Config_Debug_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:Pmd.Config)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_config_2eproto();
  friend void protobuf_AssignDesc_config_2eproto();
  friend void protobuf_ShutdownFile_config_2eproto();

  void InitAsDefaultInstance();
  static Config* default_instance_;
};
// ===================================================================


// ===================================================================

// Config


// @@protoc_insertion_point(namespace_scope)

}  // namespace Pmd

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::Pmd::Config_Version> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Pmd::Config_Version>() {
  return ::Pmd::Config_Version_descriptor();
}
template <> struct is_proto_enum< ::Pmd::Config_Debug> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Pmd::Config_Debug>() {
  return ::Pmd::Config_Debug_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_config_2eproto__INCLUDED
