// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pushpmd.proto

#ifndef PROTOBUF_pushpmd_2eproto__INCLUDED
#define PROTOBUF_pushpmd_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include "pmd.pb.h"
// @@protoc_insertion_point(includes)

namespace Pmd {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_pushpmd_2eproto();
void protobuf_AssignDesc_pushpmd_2eproto();
void protobuf_ShutdownFile_pushpmd_2eproto();

class Push;
class ClientInstallFinishPushPmd_C;
class ClientUninstallPushPmd_C;
class ClientStartPushPmd_C;
class ClientExitPushPmd_C;
class ServiceStartPushPmd_C;
class ServiceExitPushPmd_C;
class NotifyMessagePushPmd_S;

enum Push_Param {
  Push_Param_ClientInstallFinishPushPmd_C = 1,
  Push_Param_ClientUninstallPushPmd_C = 2,
  Push_Param_ClientStartPushPmd_C = 3,
  Push_Param_ClientExitPushPmd_C = 4,
  Push_Param_ServiceStartPushPmd_C = 5,
  Push_Param_ServiceExitPushPmd_C = 6,
  Push_Param_NotifyMessagePushPmd_S = 7
};
bool Push_Param_IsValid(int value);
const Push_Param Push_Param_Param_MIN = Push_Param_ClientInstallFinishPushPmd_C;
const Push_Param Push_Param_Param_MAX = Push_Param_NotifyMessagePushPmd_S;
const int Push_Param_Param_ARRAYSIZE = Push_Param_Param_MAX + 1;

const ::google::protobuf::EnumDescriptor* Push_Param_descriptor();
inline const ::std::string& Push_Param_Name(Push_Param value) {
  return ::google::protobuf::internal::NameOfEnum(
    Push_Param_descriptor(), value);
}
inline bool Push_Param_Parse(
    const ::std::string& name, Push_Param* value) {
  return ::google::protobuf::internal::ParseNamedEnum<Push_Param>(
    Push_Param_descriptor(), name, value);
}
// ===================================================================

class Push : public ::google::protobuf::Message {
 public:
  Push();
  virtual ~Push();

  Push(const Push& from);

  inline Push& operator=(const Push& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Push& default_instance();

  void Swap(Push* other);

  // implements Message ----------------------------------------------

  Push* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Push& from);
  void MergeFrom(const Push& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef Push_Param Param;
  static const Param ClientInstallFinishPushPmd_C = Push_Param_ClientInstallFinishPushPmd_C;
  static const Param ClientUninstallPushPmd_C = Push_Param_ClientUninstallPushPmd_C;
  static const Param ClientStartPushPmd_C = Push_Param_ClientStartPushPmd_C;
  static const Param ClientExitPushPmd_C = Push_Param_ClientExitPushPmd_C;
  static const Param ServiceStartPushPmd_C = Push_Param_ServiceStartPushPmd_C;
  static const Param ServiceExitPushPmd_C = Push_Param_ServiceExitPushPmd_C;
  static const Param NotifyMessagePushPmd_S = Push_Param_NotifyMessagePushPmd_S;
  static inline bool Param_IsValid(int value) {
    return Push_Param_IsValid(value);
  }
  static const Param Param_MIN =
    Push_Param_Param_MIN;
  static const Param Param_MAX =
    Push_Param_Param_MAX;
  static const int Param_ARRAYSIZE =
    Push_Param_Param_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  Param_descriptor() {
    return Push_Param_descriptor();
  }
  static inline const ::std::string& Param_Name(Param value) {
    return Push_Param_Name(value);
  }
  static inline bool Param_Parse(const ::std::string& name,
      Param* value) {
    return Push_Param_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:Pmd.Push)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_pushpmd_2eproto();
  friend void protobuf_AssignDesc_pushpmd_2eproto();
  friend void protobuf_ShutdownFile_pushpmd_2eproto();

  void InitAsDefaultInstance();
  static Push* default_instance_;
};
// -------------------------------------------------------------------

class ClientInstallFinishPushPmd_C : public ::google::protobuf::Message {
 public:
  ClientInstallFinishPushPmd_C();
  virtual ~ClientInstallFinishPushPmd_C();

  ClientInstallFinishPushPmd_C(const ClientInstallFinishPushPmd_C& from);

  inline ClientInstallFinishPushPmd_C& operator=(const ClientInstallFinishPushPmd_C& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ClientInstallFinishPushPmd_C& default_instance();

  void Swap(ClientInstallFinishPushPmd_C* other);

  // implements Message ----------------------------------------------

  ClientInstallFinishPushPmd_C* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ClientInstallFinishPushPmd_C& from);
  void MergeFrom(const ClientInstallFinishPushPmd_C& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string mid = 1;
  inline bool has_mid() const;
  inline void clear_mid();
  static const int kMidFieldNumber = 1;
  inline const ::std::string& mid() const;
  inline void set_mid(const ::std::string& value);
  inline void set_mid(const char* value);
  inline void set_mid(const char* value, size_t size);
  inline ::std::string* mutable_mid();
  inline ::std::string* release_mid();
  inline void set_allocated_mid(::std::string* mid);

  // @@protoc_insertion_point(class_scope:Pmd.ClientInstallFinishPushPmd_C)
 private:
  inline void set_has_mid();
  inline void clear_has_mid();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* mid_;
  friend void  protobuf_AddDesc_pushpmd_2eproto();
  friend void protobuf_AssignDesc_pushpmd_2eproto();
  friend void protobuf_ShutdownFile_pushpmd_2eproto();

  void InitAsDefaultInstance();
  static ClientInstallFinishPushPmd_C* default_instance_;
};
// -------------------------------------------------------------------

class ClientUninstallPushPmd_C : public ::google::protobuf::Message {
 public:
  ClientUninstallPushPmd_C();
  virtual ~ClientUninstallPushPmd_C();

  ClientUninstallPushPmd_C(const ClientUninstallPushPmd_C& from);

  inline ClientUninstallPushPmd_C& operator=(const ClientUninstallPushPmd_C& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ClientUninstallPushPmd_C& default_instance();

  void Swap(ClientUninstallPushPmd_C* other);

  // implements Message ----------------------------------------------

  ClientUninstallPushPmd_C* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ClientUninstallPushPmd_C& from);
  void MergeFrom(const ClientUninstallPushPmd_C& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:Pmd.ClientUninstallPushPmd_C)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_pushpmd_2eproto();
  friend void protobuf_AssignDesc_pushpmd_2eproto();
  friend void protobuf_ShutdownFile_pushpmd_2eproto();

  void InitAsDefaultInstance();
  static ClientUninstallPushPmd_C* default_instance_;
};
// -------------------------------------------------------------------

class ClientStartPushPmd_C : public ::google::protobuf::Message {
 public:
  ClientStartPushPmd_C();
  virtual ~ClientStartPushPmd_C();

  ClientStartPushPmd_C(const ClientStartPushPmd_C& from);

  inline ClientStartPushPmd_C& operator=(const ClientStartPushPmd_C& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ClientStartPushPmd_C& default_instance();

  void Swap(ClientStartPushPmd_C* other);

  // implements Message ----------------------------------------------

  ClientStartPushPmd_C* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ClientStartPushPmd_C& from);
  void MergeFrom(const ClientStartPushPmd_C& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:Pmd.ClientStartPushPmd_C)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_pushpmd_2eproto();
  friend void protobuf_AssignDesc_pushpmd_2eproto();
  friend void protobuf_ShutdownFile_pushpmd_2eproto();

  void InitAsDefaultInstance();
  static ClientStartPushPmd_C* default_instance_;
};
// -------------------------------------------------------------------

class ClientExitPushPmd_C : public ::google::protobuf::Message {
 public:
  ClientExitPushPmd_C();
  virtual ~ClientExitPushPmd_C();

  ClientExitPushPmd_C(const ClientExitPushPmd_C& from);

  inline ClientExitPushPmd_C& operator=(const ClientExitPushPmd_C& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ClientExitPushPmd_C& default_instance();

  void Swap(ClientExitPushPmd_C* other);

  // implements Message ----------------------------------------------

  ClientExitPushPmd_C* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ClientExitPushPmd_C& from);
  void MergeFrom(const ClientExitPushPmd_C& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:Pmd.ClientExitPushPmd_C)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_pushpmd_2eproto();
  friend void protobuf_AssignDesc_pushpmd_2eproto();
  friend void protobuf_ShutdownFile_pushpmd_2eproto();

  void InitAsDefaultInstance();
  static ClientExitPushPmd_C* default_instance_;
};
// -------------------------------------------------------------------

class ServiceStartPushPmd_C : public ::google::protobuf::Message {
 public:
  ServiceStartPushPmd_C();
  virtual ~ServiceStartPushPmd_C();

  ServiceStartPushPmd_C(const ServiceStartPushPmd_C& from);

  inline ServiceStartPushPmd_C& operator=(const ServiceStartPushPmd_C& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ServiceStartPushPmd_C& default_instance();

  void Swap(ServiceStartPushPmd_C* other);

  // implements Message ----------------------------------------------

  ServiceStartPushPmd_C* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ServiceStartPushPmd_C& from);
  void MergeFrom(const ServiceStartPushPmd_C& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:Pmd.ServiceStartPushPmd_C)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_pushpmd_2eproto();
  friend void protobuf_AssignDesc_pushpmd_2eproto();
  friend void protobuf_ShutdownFile_pushpmd_2eproto();

  void InitAsDefaultInstance();
  static ServiceStartPushPmd_C* default_instance_;
};
// -------------------------------------------------------------------

class ServiceExitPushPmd_C : public ::google::protobuf::Message {
 public:
  ServiceExitPushPmd_C();
  virtual ~ServiceExitPushPmd_C();

  ServiceExitPushPmd_C(const ServiceExitPushPmd_C& from);

  inline ServiceExitPushPmd_C& operator=(const ServiceExitPushPmd_C& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ServiceExitPushPmd_C& default_instance();

  void Swap(ServiceExitPushPmd_C* other);

  // implements Message ----------------------------------------------

  ServiceExitPushPmd_C* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ServiceExitPushPmd_C& from);
  void MergeFrom(const ServiceExitPushPmd_C& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:Pmd.ServiceExitPushPmd_C)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_pushpmd_2eproto();
  friend void protobuf_AssignDesc_pushpmd_2eproto();
  friend void protobuf_ShutdownFile_pushpmd_2eproto();

  void InitAsDefaultInstance();
  static ServiceExitPushPmd_C* default_instance_;
};
// -------------------------------------------------------------------

class NotifyMessagePushPmd_S : public ::google::protobuf::Message {
 public:
  NotifyMessagePushPmd_S();
  virtual ~NotifyMessagePushPmd_S();

  NotifyMessagePushPmd_S(const NotifyMessagePushPmd_S& from);

  inline NotifyMessagePushPmd_S& operator=(const NotifyMessagePushPmd_S& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const NotifyMessagePushPmd_S& default_instance();

  void Swap(NotifyMessagePushPmd_S* other);

  // implements Message ----------------------------------------------

  NotifyMessagePushPmd_S* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const NotifyMessagePushPmd_S& from);
  void MergeFrom(const NotifyMessagePushPmd_S& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 type = 1;
  inline bool has_type() const;
  inline void clear_type();
  static const int kTypeFieldNumber = 1;
  inline ::google::protobuf::uint32 type() const;
  inline void set_type(::google::protobuf::uint32 value);

  // optional string info = 2;
  inline bool has_info() const;
  inline void clear_info();
  static const int kInfoFieldNumber = 2;
  inline const ::std::string& info() const;
  inline void set_info(const ::std::string& value);
  inline void set_info(const char* value);
  inline void set_info(const char* value, size_t size);
  inline ::std::string* mutable_info();
  inline ::std::string* release_info();
  inline void set_allocated_info(::std::string* info);

  // @@protoc_insertion_point(class_scope:Pmd.NotifyMessagePushPmd_S)
 private:
  inline void set_has_type();
  inline void clear_has_type();
  inline void set_has_info();
  inline void clear_has_info();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* info_;
  ::google::protobuf::uint32 type_;
  friend void  protobuf_AddDesc_pushpmd_2eproto();
  friend void protobuf_AssignDesc_pushpmd_2eproto();
  friend void protobuf_ShutdownFile_pushpmd_2eproto();

  void InitAsDefaultInstance();
  static NotifyMessagePushPmd_S* default_instance_;
};
// ===================================================================


// ===================================================================

// Push

// -------------------------------------------------------------------

// ClientInstallFinishPushPmd_C

// optional string mid = 1;
inline bool ClientInstallFinishPushPmd_C::has_mid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ClientInstallFinishPushPmd_C::set_has_mid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ClientInstallFinishPushPmd_C::clear_has_mid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ClientInstallFinishPushPmd_C::clear_mid() {
  if (mid_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    mid_->clear();
  }
  clear_has_mid();
}
inline const ::std::string& ClientInstallFinishPushPmd_C::mid() const {
  // @@protoc_insertion_point(field_get:Pmd.ClientInstallFinishPushPmd_C.mid)
  return *mid_;
}
inline void ClientInstallFinishPushPmd_C::set_mid(const ::std::string& value) {
  set_has_mid();
  if (mid_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    mid_ = new ::std::string;
  }
  mid_->assign(value);
  // @@protoc_insertion_point(field_set:Pmd.ClientInstallFinishPushPmd_C.mid)
}
inline void ClientInstallFinishPushPmd_C::set_mid(const char* value) {
  set_has_mid();
  if (mid_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    mid_ = new ::std::string;
  }
  mid_->assign(value);
  // @@protoc_insertion_point(field_set_char:Pmd.ClientInstallFinishPushPmd_C.mid)
}
inline void ClientInstallFinishPushPmd_C::set_mid(const char* value, size_t size) {
  set_has_mid();
  if (mid_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    mid_ = new ::std::string;
  }
  mid_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:Pmd.ClientInstallFinishPushPmd_C.mid)
}
inline ::std::string* ClientInstallFinishPushPmd_C::mutable_mid() {
  set_has_mid();
  if (mid_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    mid_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:Pmd.ClientInstallFinishPushPmd_C.mid)
  return mid_;
}
inline ::std::string* ClientInstallFinishPushPmd_C::release_mid() {
  clear_has_mid();
  if (mid_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = mid_;
    mid_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void ClientInstallFinishPushPmd_C::set_allocated_mid(::std::string* mid) {
  if (mid_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete mid_;
  }
  if (mid) {
    set_has_mid();
    mid_ = mid;
  } else {
    clear_has_mid();
    mid_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:Pmd.ClientInstallFinishPushPmd_C.mid)
}

// -------------------------------------------------------------------

// ClientUninstallPushPmd_C

// -------------------------------------------------------------------

// ClientStartPushPmd_C

// -------------------------------------------------------------------

// ClientExitPushPmd_C

// -------------------------------------------------------------------

// ServiceStartPushPmd_C

// -------------------------------------------------------------------

// ServiceExitPushPmd_C

// -------------------------------------------------------------------

// NotifyMessagePushPmd_S

// optional uint32 type = 1;
inline bool NotifyMessagePushPmd_S::has_type() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void NotifyMessagePushPmd_S::set_has_type() {
  _has_bits_[0] |= 0x00000001u;
}
inline void NotifyMessagePushPmd_S::clear_has_type() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void NotifyMessagePushPmd_S::clear_type() {
  type_ = 0u;
  clear_has_type();
}
inline ::google::protobuf::uint32 NotifyMessagePushPmd_S::type() const {
  // @@protoc_insertion_point(field_get:Pmd.NotifyMessagePushPmd_S.type)
  return type_;
}
inline void NotifyMessagePushPmd_S::set_type(::google::protobuf::uint32 value) {
  set_has_type();
  type_ = value;
  // @@protoc_insertion_point(field_set:Pmd.NotifyMessagePushPmd_S.type)
}

// optional string info = 2;
inline bool NotifyMessagePushPmd_S::has_info() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void NotifyMessagePushPmd_S::set_has_info() {
  _has_bits_[0] |= 0x00000002u;
}
inline void NotifyMessagePushPmd_S::clear_has_info() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void NotifyMessagePushPmd_S::clear_info() {
  if (info_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    info_->clear();
  }
  clear_has_info();
}
inline const ::std::string& NotifyMessagePushPmd_S::info() const {
  // @@protoc_insertion_point(field_get:Pmd.NotifyMessagePushPmd_S.info)
  return *info_;
}
inline void NotifyMessagePushPmd_S::set_info(const ::std::string& value) {
  set_has_info();
  if (info_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    info_ = new ::std::string;
  }
  info_->assign(value);
  // @@protoc_insertion_point(field_set:Pmd.NotifyMessagePushPmd_S.info)
}
inline void NotifyMessagePushPmd_S::set_info(const char* value) {
  set_has_info();
  if (info_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    info_ = new ::std::string;
  }
  info_->assign(value);
  // @@protoc_insertion_point(field_set_char:Pmd.NotifyMessagePushPmd_S.info)
}
inline void NotifyMessagePushPmd_S::set_info(const char* value, size_t size) {
  set_has_info();
  if (info_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    info_ = new ::std::string;
  }
  info_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:Pmd.NotifyMessagePushPmd_S.info)
}
inline ::std::string* NotifyMessagePushPmd_S::mutable_info() {
  set_has_info();
  if (info_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    info_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:Pmd.NotifyMessagePushPmd_S.info)
  return info_;
}
inline ::std::string* NotifyMessagePushPmd_S::release_info() {
  clear_has_info();
  if (info_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = info_;
    info_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void NotifyMessagePushPmd_S::set_allocated_info(::std::string* info) {
  if (info_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete info_;
  }
  if (info) {
    set_has_info();
    info_ = info;
  } else {
    clear_has_info();
    info_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:Pmd.NotifyMessagePushPmd_S.info)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace Pmd

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::Pmd::Push_Param> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Pmd::Push_Param>() {
  return ::Pmd::Push_Param_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_pushpmd_2eproto__INCLUDED
